// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineShopping.DAL
{
    public partial class UserTokens
    {
        public long Id { get; set; }
        public long? UserId { get; set; }
        public string Token { get; set; }
        public DateTime? TokenExpireTime { get; set; }
        public DateTime DateTimeCreated { get; set; }
    }
}